version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/vector-drawable-previwer/extension

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
            - node-v1-
      - run: |
          npm config set spin=false
          npm config set progress=false
          npm install
      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run lint
      - run: npm run tsc
      - run: npm run browserify
      - run: zip -r build-$CIRCLE_BUILD_NUM.zip package
      - store_artifacts:
          path: package
          destination: package
      - store_artifacts:
          path: build-{{ Environment.CIRCLE_BUILD_NUM }}.zip
          destination: extension.zip

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
