
name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        cache: 'yarn'
    - uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('.node-version', './yarn.lock') }}-node_modules
    - run: yarn install --frozen-lockfile
    - run: yarn package

  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        cache: 'yarn'
    - uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('.node-version', './yarn.lock') }}-node_modules
    - run: yarn install --frozen-lockfile
    - run: yarn lint