
name: Run jobs on master

on: 
  push:
    tags:
      - v\d\.\d.\d

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        cache: 'yarn'
    - uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('.node-version', './yarn.lock') }}-node_modules
    - run: yarn install --frozen-lockfile
    - run: yarn package

    - name: Create a Release
      id: create_release
      uses: softprops/action-gh-release@v2c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
      with:
        make_latest: true
        draft: false
        prerelease: false
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: |
          ./extension.zip
